### ISSUE TITLE
Archlinux compatiblity

### ISSUE THREAD

**Issue by winiciuscota** [carlosmax3D/DS4_CLONE_DKMS_DUALSHOCK_PS4#3]
Did anyone had any success running the script on arch/manjaro?

Getting this error after I commented the lines downloading the kernel source package

```
Patching driver
patching file ./module/hid-sony.c
Hunk #1 FAILED at 2084.
Hunk #2 FAILED at 2122.
Hunk #3 FAILED at 2483.
patch: **** Can't reopen file ./module/hid-sony.c : No such file or directory
mv: cannot stat './module/hid-sony.c': No such file or directory
Creating files for building
Stopping inbuilt and new module
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/akvcam/1.2.2/source/dkms.conf does not exist.
Copying the module to DKMS
Compiling DKMS module
Error! Your kernel headers for kernel 5.17.0-1-MANJARO cannot be found at /usr/lib/modules/5.17.0-1-MANJARO/build or /usr/lib/modules/5.17.0-1-MANJARO/source.
Please install the linux-headers-5.17.0-1-MANJARO package or use the --kernelsourcedir option to tell DKMS where it's located.
rmmod: ERROR: Module hid_sony is not currently loaded
modprobe: FATAL: Module hid-sony-clone-fix not found in directory /lib/modules/5.17.0-1-MANJARO
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/akvcam/1.2.2/source/dkms.conf does not exist.

```

**Comment by carlosmax3D** [comment]
Hi, seems like Manjaro retrieve the linux source directly from the kernel's main page.

https://www.kernel.org/pub/linux/kernel/v5.x/

You have to adjust the script or execute the steps manually in order to compile and install the patch module.
The steps are the following:
1.- Query your current kernel version (uname -a)
2.- Download the kernel source for your version
3.- Extract the file hid-sony.c (it must be in drivers/hid)
4.- Patch the file
5.- Compile the module, I'm pretty sure that the Makefile generated to compile should work in manjaro too
6.- Install the module, it must be the same for Manjaro as Fedora and Ubuntu.

And that's all, the previous steps are on the script, you can take a look into the script to get the information you need and if you want to contribute to the script and add the compatibility of Manjaro, go ahead that could be nice for someone else. Ping me if you need more specific help.

**Comment by carlosmax3D** [comment]
Could you install the patch?
